"""
Django settings for squant project.

Generated by "django-admin startproject" using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import sys, os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-w^53$ld1cv+@62g63f3qh2km9fcl^@&#w506=7uqpikcc^-t7s"

# SECURITY WARNING: don"t run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["192.168.1.102", "127.0.0.1"]

DATA_UPLOAD_MAX_MEMORY_SIZE = 1024000000

# Application definition

INSTALLED_APPS = [
#    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "squant",
    "django_extensions"
]

NOTEBOOK_ARGUMENTS = [
    "--ip",
    "0.0.0.0",
    "--port",
    "5555",
    "--allow-root"
]

SQUANT_CONF = {
    "history_backend": "influxdb",
    "influxdb_settings": {
        "url": "http://192.168.1.102:8086/",
        "org": "grepcode.cn",
        "token": "DKtOsiT4GlysvbgClRPEsn5cXxruip8cgEztrVNj1k2mCybSO5WIRnTnWwrpX0L4",
        "bucket": "squant"
    },
    "test": {
        "last_range": 2,
    }
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
#    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "squant.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "squant.wsgi.application"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "dev_format": {
            "format":
            "%(asctime)s %(levelname)s %(funcName)s@%(lineno)d %(message)s"
        }
    },
    "handlers": {
        "stdout": {
            "level": "DEBUG",
            "formatter": "dev_format",
            "class": "logging.StreamHandler",
#            "stream": open(os.devnull, "w")
            "stream": sys.stderr
        }
    },
    "loggers": {
        "squant": {
            "level": "DEBUG",
            "handlers": ["stdout"],
            "propagate": True
        }
    }
}


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

#DATABASES = {
#    "default": {
#        "ENGINE": "django.db.backends.sqlite3",
#        "NAME": BASE_DIR / "db.sqlite3",
#    }
#}

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "squant",
        "USER": "root",
        "PASSWORD": "6H4VY6GPn3TrXm",
        "HOST": "192.168.1.102",
        "PORT": "3306",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
